version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
        driver: ${VOLUMES_DRIVER}

services:

### Workspace Utilities ##################################

### MySQL ################################################
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${WORKSPACE_TIMEZONE}
        volumes:
            - ${MYSQL_HOST_LOG_PATH}:/var/log/mysql
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend

 ### TomCat  ################################################
    tomcat:
        build:
            context: ./tomcat
            args:
                - TOMCAT_VERSION=${TOMCAT_VERSION}
        environment:
            - TZ=${WORKSPACE_TIMEZONE}
        ports:
            - "${TOMCAT_PORT}:8080"
        networks:
            - backend
             
