ARG JETTY_VERSION
FROM jetty:${JETTY_VERSION}

LABEL maintainer="Melon Bao <melon.bao@outlook.com>"

#ENV JAVA_TOOL_OPTIONS=\"-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n\"

EXPOSE 8080
